# Generated by Django 4.2 on 2023-05-05 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('image', models.ImageField(upload_to='images')),
                ('cost_per_sample', models.CharField(max_length=1000)),
                ('matrices', models.CharField(max_length=1000)),
                ('vol_requirements', models.CharField(max_length=1000)),
                ('species', models.CharField(max_length=1000)),
                ('pathways', models.CharField(max_length=1000)),
                ('compound_classes', models.CharField(max_length=1000)),
                ('no_of_compounds', models.CharField(max_length=1000)),
                ('quantitative', models.CharField(max_length=1000)),
                ('compound_list', models.CharField(max_length=1000)),
                ('validation', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='app1.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
