# Generated by Django 4.2 on 2023-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_order_ref_code_remove_order_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
