# Generated by Django 4.2 on 2023-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_order_user_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
